
import { GlossaryTerm } from './types';

export const DISABILITY_TYPES = [
  "Visual Impairment",
  "Hearing Impairment",
  "Mobility Impairment",
  "Cognitive/Intellectual Disability",
  "Autism Spectrum Disorder",
  "Chronic Illness",
  "Mental Health Condition",
  "Other"
];

export const TRANSLATIONS = {
  en: {
    appName: "Sahayata",
    tagline: "Your Guide to Government Schemes",
    schemeFinder: "Scheme Finder",
    documentHelper: "Document Helper",
    liveAssistance: "Live Assistance",
    community: "Community & Stories",
    disabilityType: "Type of Disability",
    selectDisability: "Select a disability type",
    age: "Age",
    enterAge: "Enter your age",
    location: "State/Region",
    enterLocation: "e.g., Maharashtra, Delhi",
    findSchemes: "Find Schemes",
    findingSchemes: "Finding schemes...",
    noSchemesFound: "No schemes found matching your criteria. Please try different options.",
    errorFindingSchemes: "An error occurred while fetching schemes. Please try again later.",
    eligibility: "Eligibility",
    benefits: "Benefits",
    documentsRequired: "Documents Required",
    applicationProcess: "Application Process",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    highContrast: "High Contrast",
    largeText: "Large Text",
    language: "Language",
    english: "English",
    hindi: "हिन्दी",
    useVoiceInput: "Use Voice Input",
    voiceInputActive: "Listening...",
    docHelperTitle: "Document & Form Guide",
    commonDocs: "Commonly Required Documents",
    docList: [
      "Aadhaar Card (Proof of Identity/Address)",
      "Disability Certificate (UDID Card)",
      "Proof of Age (Birth Certificate/School Certificate)",
      "Passport-sized Photographs",
      "Income Certificate (if applicable)",
      "Caste Certificate (if applicable)"
    ],
    glossaryTitle: "Glossary of Common Terms",
    autofill: "Demo: Autofill Form",
    autofillSuccess: "Form fields populated with demo data!",
    chatbotTitle: "AI Assistant",
    typeMessage: "Type your message here...",
    sendMessage: "Send",
    humanHelp: "Request Human Help",
    humanHelpNotice: "A request has been sent for human assistance.",
    communityTitle: "Community Stories & Tips",
    story1Title: "My Journey to Independence with a Motorized Tricycle",
    story1Content: "'Thanks to the ADIP scheme, I received a motorized tricycle. It has completely changed my life, allowing me to commute to work and be self-reliant.' - Priya S.",
    story2Title: "Navigating College with a Scholarship",
    story2Content: "'The Post-Matric Scholarship for Students with Disabilities enabled me to pursue my engineering degree without financial stress. The key was to apply early and have all my documents ready.' - Rohan M.",
    alertsTitle: "Alerts & Reminders",
    alertContent: "Reminder: The deadline to apply for the 'Saksham' scholarship is August 31st. Ensure your Disability Certificate is updated.",
  },
  hi: {
    appName: "सहायता",
    tagline: "सरकारी योजनाओं के लिए आपका मार्गदर्शक",
    schemeFinder: "योजना खोजक",
    documentHelper: "दस्तावेज़ सहायक",
    liveAssistance: "लाइव सहायता",
    community: "समुदाय और कहानियाँ",
    disabilityType: "विकलांगता का प्रकार",
    selectDisability: "विकलांगता का प्रकार चुनें",
    age: "आयु",
    enterAge: "अपनी आयु दर्ज करें",
    location: "राज्य/क्षेत्र",
    enterLocation: "उदा., महाराष्ट्र, दिल्ली",
    findSchemes: "योजनाएं खोजें",
    findingSchemes: "योजनाएं ढूंढी जा रही हैं...",
    noSchemesFound: "आपके मानदंडों से मेल खाने वाली कोई योजना नहीं मिली। कृपया भिन्न विकल्प आजमाएं।",
    errorFindingSchemes: "योजनाओं को प्राप्त करते समय एक त्रुटि हुई। कृपया बाद में पुनः प्रयास करें।",
    eligibility: "पात्रता",
    benefits: "लाभ",
    documentsRequired: "आवश्यक दस्तावेज़",
    applicationProcess: "आवेदन प्रक्रिया",
    readAloud: "पढ़कर सुनाओ",
    stopReading: "पढ़ना बंद करो",
    highContrast: "उच्च कंट्रास्ट",
    largeText: "बड़ा टेक्स्ट",
    language: "भाषा",
    english: "English",
    hindi: "हिन्दी",
    useVoiceInput: "वॉयस इनपुट का प्रयोग करें",
    voiceInputActive: "सुन रहा है...",
    docHelperTitle: "दस्तावेज़ और फॉर्म गाइड",
    commonDocs: "आमतौर पर आवश्यक दस्तावेज़",
    docList: [
      "आधार कार्ड (पहचान/पते का प्रमाण)",
      "विकलांगता प्रमाण पत्र (UDID कार्ड)",
      "आयु का प्रमाण (जन्म प्रमाण पत्र/स्कूल प्रमाण पत्र)",
      "पासपोर्ट आकार की तस्वीरें",
      "आय प्रमाण पत्र (यदि लागू हो)",
      "जाति प्रमाण पत्र (यदि लागू हो)"
    ],
    glossaryTitle: "सामान्य शब्दों की शब्दावली",
    autofill: "डेमो: फॉर्म ऑटोफिल करें",
    autofillSuccess: "डेमो डेटा के साथ फॉर्म फ़ील्ड भर दिए गए हैं!",
    chatbotTitle: "एआई सहायक",
    typeMessage: "अपना संदेश यहां टाइप करें...",
    sendMessage: "भेजें",
    humanHelp: "मानव सहायता का अनुरोध करें",
    humanHelpNotice: "मानव सहायता के लिए अनुरोध भेजा गया है।",
    communityTitle: "सामुदायिक कहानियाँ और सुझाव",
    story1Title: "मोटर चालित तिपहिया वाहन के साथ स्वतंत्रता की मेरी यात्रा",
    story1Content: "'एडीआईपी योजना के लिए धन्यवाद, मुझे एक मोटर चालित तिपहिया वाहन मिला। इसने मेरे जीवन को पूरी तरह से बदल दिया है, जिससे मुझे काम पर आने-जाने और आत्मनिर्भर बनने में मदद मिली है।' - प्रिया एस.",
    story2Title: "छात्रवृत्ति के साथ कॉलेज नेविगेट करना",
    story2Content: "'विकलांग छात्रों के लिए पोस्ट-मैट्रिक छात्रवृत्ति ने मुझे बिना किसी वित्तीय तनाव के अपनी इंजीनियरिंग की डिग्री हासिल करने में सक्षम बनाया। मुख्य बात यह थी कि जल्दी आवेदन करें और मेरे सभी दस्तावेज तैयार रखें।' - रोहन एम.",
    alertsTitle: "अलर्ट और अनुस्मारक",
    alertContent: "अनुस्मारक: 'सक्षम' छात्रवृत्ति के लिए आवेदन करने की अंतिम तिथि 31 अगस्त है। सुनिश्चित करें कि आपका विकलांगता प्रमाण पत्र अद्यतन है।",
  }
};

export const GLOSSARY_TERMS: { en: GlossaryTerm[], hi: GlossaryTerm[] } = {
    en: [
        { term: "UDID Card", definition: "Unique Disability ID card, a single document for persons with disabilities to avail various government schemes and benefits." },
        { term: "Aadhaar Card", definition: "A 12-digit unique identity number issued by the Indian government to every resident of India." },
        { term: "Beneficiary", definition: "A person who receives benefits or advantages from a scheme or policy." }
    ],
    hi: [
        { term: "यूडीआईडी कार्ड", definition: "विशिष्ट विकलांगता आईडी कार्ड, विकलांग व्यक्तियों के लिए विभिन्न सरकारी योजनाओं और लाभों का लाभ उठाने के लिए एक एकल दस्तावेज।" },
        { term: "आधार कार्ड", definition: "भारत सरकार द्वारा भारत के प्रत्येक निवासी को जारी किया गया 12 अंकों का विशिष्ट पहचान संख्या।" },
        { term: "लाभार्थी", definition: "एक व्यक्ति जो किसी योजना या नीति से लाभ या फायदे प्राप्त करता है।" }
    ]
};
